databases:
  - name: pokemonsterdb
    plan: free
    databaseName: pokemonster
    user: pokemonster

services:
  - type: web
    plan: free
    name: pokemonster
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn pokemonster.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pokemonsterdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
