# Generated by Django 4.0.3 on 2022-04-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_profile_description_alter_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('type', models.CharField(choices=[('Cure', 'Cure'), ('Annoying', 'Annoying'), ('Funny', 'Funny')], max_length=8)),
                ('likes', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('customon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customon')),
            ],
        ),
    ]
