# Generated by Django 4.0.3 on 2022-04-29 07:12

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('type', models.CharField(choices=[('Cute', 'Cute'), ('Annoying', 'Annoying'), ('Funny', 'Funny'), ('Angry', 'Angry'), ('Sad', 'Sad'), ('Amazing', 'Amazing')], max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('customon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
