# Generated by Django 4.0.3 on 2022-04-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_cash'),
        ('main', '0003_alter_customon_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customon',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customon',
            name='type',
            field=models.CharField(choices=[('Cute', 'Cute'), ('Annoying', 'Annoying'), ('Funny', 'Funny')], max_length=8),
        ),
    ]
