# Generated by Django 4.0.3 on 2022-04-23 19:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_customon_likes_comment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customon',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='customon',
            name='type',
            field=models.CharField(choices=[('Cute', 'Cute'), ('Annoying', 'Annoying'), ('Funny', 'Funny'), ('Angry', 'Angry'), ('Sad', 'Sad'), ('Amazing', 'Amazing')], max_length=8),
        ),
    ]
