# Generated by Django 4.0.3 on 2022-04-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customon_photo_alter_customon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customon',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
