# Generated by Django 4.0.3 on 2022-04-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_cash'),
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.BooleanField()),
                ('bet_amount', models.IntegerField()),
                ('chosen_pokemon', models.ManyToManyField(related_name='chosen', to='fight.pokemon')),
                ('enemy_pokemon', models.ManyToManyField(related_name='enemy', to='fight.pokemon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
