# Generated by Django 4.0.3 on 2022-04-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0003_remove_fight_chosen_pokemon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='selected_pokemon',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
