# Generated by Django 4.0.3 on 2022-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0004_fight_selected_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='fight_log',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
