# Generated by Django 4.0.3 on 2022-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_description_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cash',
            field=models.IntegerField(default=1000),
        ),
    ]
