# Generated by Django 4.0.3 on 2022-04-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_gender_profile_faction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='faction',
            field=models.CharField(blank=True, choices=[('Mystic', 'Mystic'), ('Instinct', 'Instinct'), ('Valor', 'Valor'), ('Unaffiliated', 'Unaffiliated')], default='Unaffiliated', max_length=12, null=True),
        ),
    ]
